services:
  ollama:
      image: ollama/ollama:0.3.0
      container_name: ollama
      restart: unless-stopped
      environment:
        - OLLAMA_DEBUG=0
      ports:
        - ${OLLAMA_PORT}:11434
      volumes:
        - ./ollama:/root/.ollama

  mongo:
    image: bitnami/mongodb:7.0-debian-12
    container_name: mongo
    restart: unless-stopped
    environment:
      - MONGODB_ROOT_USER=${MONGO_USERNAME}
      - MONGODB_ROOT_PASSWORD=${MONGO_PASSWORD}
      - MONGODB_DISABLE_SYSTEM_LOG=true
    ports:
      - ${MONGO_PORT}:27017
    volumes:
      - ./mongo:/bitnami/mongodb

  express:
    image: mongo-express:1.0
    container_name: express
    restart: unless-stopped
    depends_on:
      - mongo
    ports:
      - ${ME_PORT}:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_USERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_PASSWORD}
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_PORT=${MONGO_PORT}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_USER}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_PASSWORD}
    
  chroma:
    image: ghcr.io/chroma-core/chroma:latest
    container_name: chroma
    volumes:
      - ./chroma:/chroma/chroma
    ports:
      - ${CHROMA_PORT}:8000